In [2]:
import numpy as np

In [3]:
matrix = [[0, 1, 1, 0, 2,],
            [2, 0, 1, 0, 0,],
            [0, 0, 0, 1, 0,],
            [0, 0, 0, 0, 1,],
            [0, 0, 0, 0, 0,]] 
matrix = np.array(matrix)

In [9]:
matrix[1][0]

2

In [11]:
list(zip(*np.where(matrix == 2)))

[(0, 4), (1, 0)]

In [23]:
%timeit hash(matrix.tostring())

<magic-timeit>:1: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.


371 ns ± 4.19 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [28]:
hash(matrix.tobytes())

-1188957531729811018

In [42]:
matrix[0][0] = 1
print(hash(matrix.tobytes()))
matrix[0][0] = 0
matrix[3][4] = 2
print(str(hash(matrix.tobytes())) + str(1))
(type(str(hash(matrix.tobytes()))))
# fast and consistent

7767091685734932457
-24170214344924240531


str

7767091685734932457
-2417021434492424053

In [45]:
np.count_nonzero(matrix == 1)

5

In [50]:
np.savetxt('test.txt', matrix.astype(int), delimiter=',')

In [8]:
print(matrix)
matrix[-4][0]

[[0 1 1 0 2]
 [2 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]]


2

```python
def iter_deep_ab_search(root_node) -> Move:
    start_time = current_time
    best_move = None
    for cur_depth in range(MIN_DEPTH, MAX_DEPTH+1, STEP):
        best_move = ab_search(root_node, cur_depth)
        if current_time-start_time >= TIME_LIMIT: break
    return best_move
```